name: SJQU-Health-Report

on:
  workflow_dispatch:
  schedule:
    - cron: "00 12 * * *"
    - cron: "30 12 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install GenchAPI
    - name: Run with VPN
      env:
        username: ${{ secrets.username }}
        password: ${{ secrets.password }}
      uses: zhangt2333/actions-easyconnect@main
      with:
        CLI_OPTS: -d 'https://vpn.gench.edu.cn' -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}
        RETRY: 2
        SLEEP_AFTER_LOGIN: 1
        EXPECTED_EXIT_CODE: 66
        SCRIPT: |
          python main.py
